import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.SUPABASE_URL!
const supabaseAnonKey = process.env.SUPABASE_ANON_KEY!

export const supabase = createClient(supabaseUrl, supabaseAnonKey)

// For server-side operations that need elevated permissions
export const supabaseAdmin = createClient(
  supabaseUrl,
  process.env.SUPABASE_SERVICE_KEY!,
  {
    auth: {
      autoRefreshToken: false,
      persistSession: false
    }
  }
)

// Database types for TypeScript (generated by Supabase CLI)
export type Database = {
  public: {
    Tables: {
      posts: {
        Row: {
          id: string
          title: string
          slug: string
          content: string
          excerpt: string | null
          published: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          title: string
          slug: string
          content: string
          excerpt?: string | null
          published?: boolean
        }
        Update: {
          title?: string
          slug?: string
          content?: string
          excerpt?: string | null
          published?: boolean
        }
      }
      // Add other tables as needed
    }
  }
}